sylius_twig_hooks:
    hooks:
        'sylius_paypal.shop.pay_with_paypal.content':
            flashes:
                template: '@SyliusPayPalPlugin/shop/pay_with_paypal/content/flashes.html.twig'
                priority: 400
            paypal:
                template: '@SyliusPayPalPlugin/shop/pay_with_paypal/content/methods/paypal.html.twig'
                priority: 300
            paypal_messaging:
                template: '@SyliusPayPalPlugin/shop/pay_with_paypal/content/paypal_messaging.html.twig'
                priority: 250
            venmo:
                template: '@SyliusPayPalPlugin/shop/pay_with_paypal/content/methods/venmo.html.twig'
                priority: 225
            google_pay:
                template: '@SyliusPayPalPlugin/shop/pay_with_paypal/content/methods/google_pay.html.twig'
                priority: 200
            redirect_methods:
                template: '@SyliusPayPalPlugin/shop/pay_with_paypal/content/methods/redirect.html.twig'
                priority: 150
            card:
                template: '@SyliusPayPalPlugin/shop/pay_with_paypal/content/methods/card.html.twig'
                priority: 100
            privacy_notice:
                template: '@SyliusPayPalPlugin/shop/pay_with_paypal/content/privacy_notice.html.twig'
                priority: 0

        'sylius_paypal.shop.pay_with_paypal.content.flashes':
            messages:
                template: '@SyliusShop/shared/flashes.html.twig'
                priority: 0
