sylius_paypal_admin_download_payouts_report:
    path: /download/payouts-report/{id}
    methods: [GET]
    defaults:
        _controller: sylius_paypal.controller.download_payouts_report

sylius_paypal_admin_enable_seller:
    path: /enable-seller/{id}
    methods: [POST]
    defaults:
        _controller: sylius_paypal.controller.enable_seller

sylius_paypal_admin_complete_onboarding:
    path: /onboarding/complete
    methods: [POST]
    defaults:
        _controller: sylius_paypal.controller.complete_onboarding
