sylius_paypal_admin:
    resource: "@SyliusPayPalPlugin/config/routes/admin.yaml"
    prefix: '/%sylius_admin.path_name%'

sylius_paypal_shop:
    resource: "@SyliusPayPalPlugin/config/routes/shop.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/config/routes/webhook.yaml"

sylius_paypal_callback:
    resource: "@SyliusPayPalPlugin/config/routes/callback.yaml"
