sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.index.content.grid':
            confirmation_modal_create_paypal:
                template: '@SyliusPayPalPlugin/admin/payment_method/grid/confirmation_modal_create_paypal.html.twig'
                priority: -100
            confirmation_modal_create_paypal_sandbox:
                template: '@SyliusPayPalPlugin/admin/payment_method/grid/confirmation_modal_create_paypal_sandbox.html.twig'
                priority: -200

        'sylius_admin.payment_method.index.content.grid.data_table#suggested':
            paypal:
                template: '@SyliusPayPalPlugin/admin/payment_method/index/content/grid/data_table/suggested/paypal.html.twig'
                priority: 300
